import Head from 'next/head';
import { useDispatch } from 'react-redux';
import { enquireScreen } from 'enquire-js';
import DefalutLayout from '@/layouts/defalut';
import '@/styles/globals.css';
import { wrapper } from '@/utils/reduxInit';
import Message from '@/components/Message';

// https://ithelp.ithome.com.tw/articles/10269342
// https://vercel.com/archer102125220/resume-web

function MyApp({ Component, pageProps, router, err }) {
  const dispatch = useDispatch();
  const systemEnquireScreen = (payload, callback) =>
    dispatch({ type: 'system/enquireScreen', payload, callback });

  const enquireHandler = enquireScreen(
    (mobile) => {
      systemEnquireScreen(mobile ? true : false);
    } /*, '(max-width: 1024px)' */
  );

  const Layout = LayoutSwitch(router, err);
  return (
    <Layout {...pageProps}>
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} enquireHandler={enquireHandler} />
      <Message />
    </Layout>
  );
}

function LayoutSwitch() {
  return DefalutLayout;
}

export default wrapper.withRedux(MyApp);
